const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const {AppState} = require('../electron/state.cjs');
const {Orchestrator} = require('../electron/orchestrator.cjs');
const {PreviewManager} = require('../electron/preview-manager.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'imx-projects-'));
const repo=path.join(root,'site');fs.mkdirSync(repo);
function git(args,cwd=repo){return execFileSync('git',args,{cwd,encoding:'utf8'}).trim();}
git(['init','-b','main']);git(['config','user.name','Test']);git(['config','user.email','test@example.com']);
fs.writeFileSync(path.join(repo,'index.html'),'<h1>primeira entrega</h1>');git(['add','.']);git(['commit','-m','initial']);
const state=new AppState(path.join(root,'state'));
const opened=[];
const previews=new PreviewManager({baseEnv:process.env,openExternal:async url=>opened.push(url)});
const manager=new Orchestrator({terminalManager:{killMission(){}},state,codexPath:'unused',baseEnv:process.env,worktreesRoot:path.join(root,'worktrees'),emit(){}});
(async()=>{
 const draft=manager.createMission({name:'Loja',cwd:repo,agentCount:1});
 assert.throws(()=>manager.createMission({name:'Duplicado',cwd:repo}),/já pertence/);
 const renamed=manager.renameMission(draft.id,'Loja Aurora');assert.equal(renamed.name,'Loja Aurora');
 const plan={strategy:'test',tasks:[{id:'front',role:'Frontend',title:'UI',instructions:'test'}]};
 const m=manager.getMission(draft.id);m.round=1;m.plan=plan;m.executionCwd=repo;
 await manager.prepareWorkspaces(m);assert.equal(m.workspaceMode,'worktree');const first=m.resultPath;
 fs.writeFileSync(path.join(first,'index.html'),'<h1>resultado integrado</h1>');git(['add','.'],first);git(['commit','-m','delivery'],first);
 const original=git(['rev-parse','HEAD']);m.round=2;m.executionCwd=first;
 await manager.prepareWorkspaces(m);assert.equal(m.workspaceMode,'worktree');assert.notEqual(m.resultPath,first);
 assert.match(fs.readFileSync(path.join(m.resultPath,'index.html'),'utf8'),/resultado integrado/);
 assert.equal(git(['rev-parse','HEAD']),original);assert.equal(git(['branch','--show-current']),'main');
 manager.executeMission=async mission=>{mission.status='done';mission.summary='ok';manager.snapshot(mission)};
 m.brief='Construir loja';m.status='done';m.summary='Última entrega';manager.snapshot(m);
 const next=manager.startMission({missionId:m.id,brief:'Deixar o botão verde',agentCount:1,autoEdit:true});
 assert.equal(next.id,draft.id);assert.equal(next.round,3);assert.equal(next.currentRequest,'Deixar o botão verde');
 assert.equal(next.executionCwd,m.resultPath);assert.match(manager.planningBrief(m),/Deixar o botão verde/);
 await manager.executions.get(m.id);await Promise.resolve();
 const preview=await previews.open(m);assert.match(preview.url,/^http:\/\/127\.0\.0\.1:\d+$/);
 const html=await (await fetch(preview.url)).text();assert.match(html,/resultado integrado/);
 const again=await previews.open(m);assert.equal(again.url,preview.url);assert.equal(opened.length,2);
 const secret=path.join(root,'secret.txt');fs.writeFileSync(secret,'SECRET');fs.symlinkSync(secret,path.join(m.resultPath,'leak.txt'));
 assert.equal((await fetch(preview.url+'/leak.txt')).status,403);
 m.status='running';manager.snapshot(m);assert.throws(()=>manager.deleteMission(m.id),/Cancele/);
 m.status='done';manager.snapshot(m);assert.equal(manager.deleteMission(m.id),true);
 assert.ok(fs.existsSync(path.join(m.resultPath,'index.html')));
 assert.equal(new AppState(path.join(root,'state')).listMissions().length,0);
 // Vite preview must choose a different port and retain its process until disposal.
 const viteRoot=path.join(root,'vite');fs.mkdirSync(viteRoot);
 fs.writeFileSync(path.join(viteRoot,'package.json'),JSON.stringify({scripts:{dev:'vite'},devDependencies:{vite:'*'}}));
 fs.writeFileSync(path.join(viteRoot,'index.html'),'<h1>vite-preview-ok</h1>');
 fs.symlinkSync(path.resolve(__dirname,'../node_modules'),path.join(viteRoot,'node_modules'),'dir');
 const vite=await previews.open({id:'vite-project',cwd:viteRoot});
 assert.notEqual(vite.url,preview.url);assert.match(await (await fetch(vite.url)).text(),/vite-preview-ok/);
 await previews.dispose();
 let closed=false;try{await fetch(vite.url)}catch{closed=true}assert.equal(closed,true);
 console.log('PASS: persistência, renomear/excluir preservando arquivos, proteção de execução ativa, continuidade em worktrees reais, branch original intacta, prévias HTML/Vite, isolamento de portas, bloqueio de symlink e encerramento de servidores');
})().catch(async error=>{console.error(error);await previews.dispose();process.exitCode=1}).finally(()=>fs.rmSync(root,{recursive:true,force:true}));
